name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      # ✅ Add this step to install browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --reporter=dot

      # ✅ Upload HTML test report as artifact
      - name: Upload Playwright Report
        if: always()  # ensures report uploads even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-result/
